package com.byborgenterprises.controllers;

import com.byborgenterprises.dtos.ReportDto;
import com.byborgenterprises.factories.ResponseFactory;
import lombok.NonNull;

/**
 * The ReportController interface defines operations for handling reports
 * generated by the system. It provides a method for submitting reports
 * encapsulated in a {@link ReportDto}.
 *
 * <p>The method returns a {@link ResponseFactory} to indicate the success
 * or failure of the report submission.
 */
public interface ReportController {

  /**
   * Submits a report to the external API.
   *
   * @param reportDto the report data to be submitted, encapsulated in a {@link ReportDto}.
   * @return a {@link ResponseFactory} indicating the result of the report submission.
   */
  @NonNull
  ResponseFactory<Void> postReport(@NonNull final ReportDto reportDto);
}
